/**
 * event.js
 *
 * 席次表の更新イベント一覧
 */


export default {

    EVENT_CHANGE_TABLE_TYPE: 'EVENT_CHANGE_TABLE_TYPE',
    EVENT_CHANGE_TABLE_TOTAL: 'EVENT_CHANGE_TABLE_TOTAL',

    EVENT_DELETE_GUEST: 'EVENT_DELETE_GUEST',

    EVENT_PUSH_TABLE: 'EVENT_PUSH_TABLE',
    EVENT_POP_TABLE: 'EVENT_POP_TABLE',
    EVENT_SWAP_TABLE: 'EVENT_SWAP_TABLE',

    EVENT_PUSH_GUEST: 'EVENT_PUSH_GUEST',
    EVENT_POP_GUEST: 'EVENT_POP_GUEST',
    EVENT_SWAP_GUEST: 'EVENT_SWAP_GUEST',
    EVENT_MOVE_GUEST: 'EVENT_MOVE_GUEST',

};